Improves carousel component and add usage documentation (#131)
necelentano/finec-mgimo-v2 pull request #135
Opened 2022-06-13 16:32 UTC by super16

Доработана карусель, что теперь её можно переиспользовать в разных местах, а также написана документация к компоненту

2022-06-13 20:50 UTC, epogrebnyak requested changes

2022-06-13 20:50 UTC, epogrebnyak commented on content/ru/blog/2022-06-09-graduates-2022/index.md
> +{{< carousel file-name="graduates-2022" items="1" full-height="515" height="425" unit="px" duration="4000" >}}
Немного сливается со слагом в голове - может переменную сделать data-file-name, а то первое о чем думаешь, что это дублируется адрес размещения карусели

2022-06-13 20:50 UTC, epogrebnyak commented on docs/shortcodes.md
> +# Компоненты
Дополнительные компоненты

2022-06-13 20:50 UTC, epogrebnyak commented on docs/shortcodes.md
> +  - image: /data/1.png
Удобно же картинки хранить в каталоге блога, в data будет наслоение из имиджей. Может по дефолту как было оставить - путь - смотреть из каталога где запись блога, указывать здесь только имя файла

2022-06-13 20:51 UTC, epogrebnyak commented on docs/shortcodes.md
> +  - image: /data/1.png
Это наверное больше всего обращает внимание из трёх вопросов, но не знаю это коммент к документации или к самой реализации

2022-06-14 19:45 UTC, super16 commented on docs/shortcodes.md
> +  - image: /data/1.png
> Может по дефолту как было оставить - путь - смотреть из каталога где запись блога, указывать здесь только имя файла

Это ограничивает применение компонента только для записей блога, здесь `/data/1.png` это пример, тут может быть любой абсолютный путь к файлу

2022-06-14 20:23 UTC, super16 commented on content/ru/blog/2022-06-09-graduates-2022/index.md
> +{{< carousel file-name="graduates-2022" items="1" full-height="515" height="425" unit="px" duration="4000" >}}
Заменил на `data-file-name`

2022-06-14 20:23 UTC, super16 commented on docs/shortcodes.md
> +# Компоненты
Заменил

2022-06-14 20:35 UTC, epogrebnyak requested changes

2022-06-14 20:35 UTC, epogrebnyak commented on docs/shortcodes.md
> +  - image: /data/1.png
Тогда может так в доке и пропишем - указываете локальный путь, будет локальный,укажете абсолютный - будет там. В качестве примера пути ябы все таки /data не использовал,/images может быть или /static?

2022-06-15 07:05 UTC, merged